#!/bin/bash

source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate

cd ${OPENSHIFT_REPO_DIR}

# This is a temporary workaround until this issue is resolved:
# https://github.com/openshift/origin-server/issues/6390
pip install -r requirements.txt --no-cache-dir

python manage.py migrate --no-input
python manage.py collectstatic --no-input
