# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 17:55


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0002_auto_20161201_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceanswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='balancer.BalanceResult'),
        ),
    ]
