# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0004_auto_20161202_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceanswer',
            name='match',
        ),
    ]
