# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-09 11:01


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0005_remove_balanceanswer_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceanswer',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='balancer.BalanceResult'),
        ),
    ]
