# Generated by Django 3.2.12 on 2022-02-24 20:14

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0006_auto_20170109_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceanswer',
            name='teams',
            field=jsonfield.fields.JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
