# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-01-30 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('discord_id', models.PositiveIntegerField(unique=True)),
                ('entry_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockJokeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticket', models.CharField(max_length=200)),
                ('discord_server_id', models.PositiveIntegerField()),
                ('greed_role_id', models.PositiveIntegerField()),
                ('red_role_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
