# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-01-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_joke', '0002_auto_20210130_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockjokesettings',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
