# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-01-30 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_joke', '0003_stockjokesettings_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockjokesettings',
            old_name='stock_ticket',
            new_name='stock_ticker',
        ),
    ]
