# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
