# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 13:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0002_auto_20161128_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
