# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 08:44


import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0007_player_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField()),
                ('info', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ladder.Match')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='scorechange',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Player'),
        ),
    ]
