# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0009_auto_20161204_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorechange',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ladder.MatchPlayer'),
        ),
    ]
