# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0010_auto_20161204_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorechange',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='player',
            name='ladder_mmr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorechange',
            name='mmr_change',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorechange',
            name='amount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='scorechange',
            unique_together=set([('player', 'match')]),
        ),
    ]
