# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0005_remove_balanceanswer_match'),
        ('ladder', '0011_auto_20161205_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='balance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='balancer.BalanceAnswer'),
        ),
    ]
