# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 19:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0012_match_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dota_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
