# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 12:18


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0014_auto_20161226_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorechange',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ladder.MatchPlayer'),
        ),
    ]
