# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0016_auto_20161227_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='mmr',
            new_name='dota_mmr',
        ),
    ]
