# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0017_auto_20161227_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
