# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0020_player_voice_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bot_access',
            field=models.BooleanField(default=False),
        ),
    ]
