# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0022_player_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='blacklist',
            field=models.ManyToManyField(to='ladder.Player'),
        ),
    ]
