# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-14 14:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0025_player_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='max_allowed_mmr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='min_allowed_mmr',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
