# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-23 13:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0027_auto_20170120_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='dota_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
