# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0028_match_dota_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='banned',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
