# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0029_auto_20180625_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='banned',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Not banned'), (1, 'Banned from playing only'), (2, 'Banned from playing and lobby')]),
        ),
    ]
