# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0031_auto_20180626_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
