# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0032_player_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='vouched',
            field=models.BooleanField(default=False),
        ),
    ]
