# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-31 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0006_auto_20170109_1401'),
        ('ladder', '0033_player_vouched'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('min_mmr', models.PositiveIntegerField(default=0)),
                ('lobby_name', models.CharField(max_length=200, null=True)),
                ('balance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='balancer.BalanceAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='QueuePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Player')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.LadderQueue')),
            ],
        ),
        migrations.AddField(
            model_name='ladderqueue',
            name='players',
            field=models.ManyToManyField(through='ladder.QueuePlayer', to='ladder.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='queueplayer',
            unique_together=set([('player', 'queue')]),
        ),
    ]
