# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-31 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0035_auto_20200831_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladderqueue',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ladder.QueueChannel'),
            preserve_default=False,
        ),
    ]
