# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-31 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0036_ladderqueue_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladderqueue',
            name='balance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balancer.BalanceAnswer'),
        ),
        migrations.AlterField(
            model_name='ladderqueue',
            name='lobby_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
