# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-07 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0037_auto_20200831_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laddersettings',
            name='normal_queue_discord_channel',
        ),
        migrations.RemoveField(
            model_name='laddersettings',
            name='open_queue_discord_channel',
        ),
    ]
