# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0039_remove_ladderqueue_lobby_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddersettings',
            name='mmr_per_game',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
