# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-08 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0040_laddersettings_mmr_per_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ladderqueue',
            options={'ordering': ('-id',)},
        ),
    ]
