# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0041_auto_20200908_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='new_reg_pings',
            field=models.BooleanField(default=False),
        ),
    ]
