# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0043_player_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='queue_afk_ping',
            field=models.BooleanField(default=True),
        ),
    ]
