# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-10 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0044_player_queue_afk_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddersettings',
            name='afk_allowed_time',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='laddersettings',
            name='afk_response_time',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
