# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0046_rolespreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='roles',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ladder.RolesPreference'),
        ),

    ]
