# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-12 15:16
from __future__ import unicode_literals

from django.db import migrations


def create_roles_prefs(apps, schema_editor):
    Player = apps.get_model('ladder', 'Player')
    RolesPreference = apps.get_model('ladder', 'RolesPreference')

    for player in Player.objects.all():
        roles = RolesPreference()
        roles.save()
        player.roles = roles
        player.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0047_player_roles'),
    ]

    operations = [
        migrations.RunPython(create_roles_prefs),
    ]
