# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-15 15:31
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0048_auto_20200912_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='roles',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ladder.RolesPreference'),
        ),
    ]
