# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0049_auto_20200915_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polls', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
