# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-18 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0050_discordchannels'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordPolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message_id', models.PositiveIntegerField()),
            ],
        ),
    ]
