# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-18 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0051_discordpolls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscordPolls',
            new_name='DiscordPoll',
        ),
    ]
