# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0052_auto_20200918_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddersettings',
            name='draft_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Auto balance'), (1, 'Player draft')], default=0),
        ),
    ]
