# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-19 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0053_laddersettings_draft_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannels',
            name='queues',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuechannel',
            name='discord_msg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discordchannels',
            name='polls',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
