# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0056_auto_20200919_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddersettings',
            name='balance_exponent',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
