# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0057_laddersettings_balance_exponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladderqueue',
            name='game_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ladderqueue',
            name='game_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
