# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0058_auto_20200924_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladderqueue',
            name='game_server',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
