# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-26 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0059_ladderqueue_game_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannels',
            name='chat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
