# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0060_discordchannels_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='vouch_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
