# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0061_player_vouch_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddersettings',
            name='votekick_treshold',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
