# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-05 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0064_auto_20210208_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladderqueue',
            name='max_mmr',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuechannel',
            name='max_mmr',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
