# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-07-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0065_auto_20210405_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='laddersettings',
            name='noob_queue_suffix',
            field=models.CharField(default='LUL', max_length=10),
        ),
    ]
