# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-07-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0066_laddersettings_noob_queue_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laddersettings',
            name='noob_queue_suffix',
            field=models.CharField(blank=True, default='LUL', max_length=10),
        ),
    ]
