# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-07-13 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0069_queuechannel_active_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuechannel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='queuechannel',
            name='active_on',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=(0, 1, 2, 3, 4, 5, 6), max_length=13),
        ),
    ]
