# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-01-12 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0073_auto_20211211_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuechannel',
            name='game_mode',
            field=models.CharField(choices=[('AP', 'All Pick'), ('AR', 'All Random'), ('RD', 'Random Draft'), ('SD', 'Single Draft'), ('CD', 'Captains Draft'), ('CM', 'Captains Mode'), ('RCM', 'Reverse Captains Mode'), ('ARDM', 'All Random Death Match'), ('AD', 'Ability Draft')], default='CM', max_length=200),
        ),
        migrations.AlterField(
            model_name='queuechannel',
            name='active_on',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=(0, 1, 2, 3, 4, 5, 6), max_length=13, null=True),
        ),
    ]
