# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-01-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0074_auto_20220112_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuechannel',
            name='record_matches',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='queuechannel',
            name='active_on',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=(0, 1, 2, 3, 4, 5, 6), max_length=13, null=True),
        ),
    ]
