# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2024-02-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0076_auto_20240220_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannels',
            name='chat',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discordchannels',
            name='polls',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discordchannels',
            name='queues',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discordpoll',
            name='message_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ladderqueue',
            name='game_server',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuechannel',
            name='active_on',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=(0, 1, 2, 3, 4, 5, 6), max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='queuechannel',
            name='discord_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='queuechannel',
            name='discord_msg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
