# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2024-03-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0079_auto_20240228_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=32)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('value', models.SmallIntegerField(choices=[(1, 'Positive'), (-1, 'Negative')])),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_from', to='ladder.Player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Match')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_to', to='ladder.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='queuechannel',
            name='active_on',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=(0, 1, 2, 3, 4, 5, 6), max_length=13, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='playerreport',
            unique_together=set([('from_player', 'to_player', 'match')]),
        ),
    ]
