# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2024-03-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0080_auto_20240315_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannels',
            name='queue_counter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuechannel',
            name='active_on',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=(0, 1, 2, 3, 4, 5, 6), max_length=13, null=True),
        ),
    ]
